project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Math 141"
  image: assets/math141-hex.png
  site-url: "https://www.math-141.github.io/"
  favicon: assets/favicon.ico
  navbar:
    title: false
    logo: assets/math141-hex.png
    logo-alt: "Math 141 logo"
    background: white
    foreground: "gray-800"
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Slides
        menu:
          - href: slides/math141_wk01wed.qmd
            text: "Week 1 Wednesday"
      - href: assignments.qmd
        text: Assignments
    tools:
      - icon: chat-fill
        href: https://join.slack.com/t/reedmath141fall2025/shared_invite/zt-3blne8yip-sTe8uLWC4UbexLAAA7Z~Vw
      # - icon: bar-chart-fill
      #   href: https://www.gradescope.com/courses/XXXXX
      #   aria-label: Gradescope
      - icon: r-circle-fill
        href: https://rstudio.reed.edu/
        aria-label: RStudio Server

format:
  html:
    theme:
      - sandstone
      - assets/styles.scss
    toc: true

resources: 
  - CNAME

editor: visual

