---
title: "Lecture Recordings"
subtitle: "FOR 128: Practical Computing and Data Science Tools, Fall 2024"
editor: 
  mode: source
---

## Recordings

Week 1, day 1: *Welcome to the course*. Available [here](https://mediaspace.msu.edu/media/Week+1+Day+1/1_33yh2vbh).

Week 1, day 2: *Data science tools*. Available [here](https://mediaspace.msu.edu/media/Week+1+Day+2/1_at4prglo).

Week 2, day 1: *Practical computing*. Available [here](https://mediaspace.msu.edu/media/FOR+128+F24A+Week+2+Day+1/1_zs9on3pq).

Week 2, day 2: *Reading and writing data*. Available [here](https://mediaspace.msu.edu/media/FOR+128+F24A+Week+2+Day+2/1_doi7g8ki?st=43).

Week 3, day 1: No recording available.

Week 3, day 2: *Data structures*. Available [here]( https://mediaspace.msu.edu/media/Kaltura+Capture+recording+-+September+12th+2024%2C+9A13A53+am/1_xczop9dq).

Week 4, day 1: No recording available.

Week 4, day 2: *Review of data structures & intro to functions*. Available [here](https://mediaspace.msu.edu/media/Week+4+Day+2/1_fjcmm6ye).

Week 5, day 1: *Functions and conditionals*. Available [here](https://mediaspace.msu.edu/media/Week+5+Day+1/1_ocxl3noi).

Week 5, day 2: *Functions*. NOTE: audio issues. Available [here](https://mediaspace.msu.edu/media/Week+5+Day+2/1_yjtv1zs0).

Week 6, day 1: *Welcome to the `tidyverse`*. Available [here](https://mediaspace.msu.edu/media/Week+6+Day+1/1_nots601p).

Week 6, day 2: *Midterm review day*. No recording. 

Week 7, day 1: *`tibble` and `readr`*. Available [here](https://mediaspace.msu.edu/media/Week+7+Day+1/1_dczpvt0j).

Week 7, day 2: *Introduction to data wrangling with `dplyr`*. Available [here](https://mediaspace.msu.edu/media/Week+7+Day+2/1_nya16n6e).

Week 8, day 1: *More data wrangling with `dplyr`*. Available [here](https://mediaspace.msu.edu/media/Week+8+Day+1/1_frf0qumj).

Week 8, day 2: *Advanced grouping and summarizing*. Available [here](https://mediaspace.msu.edu/media/Week+8+Day+2/1_b1tbbqza).

Week 9, day 1: *Combining multiple tibbles*. Available [here](https://mediaspace.msu.edu/media/Week+9+Day+1/1_rbv1djpc).

Week 10, day 1: *Reshaping data with `tidyr`*. Available [here](https://mediaspace.msu.edu/media/Week+10+Day+1/1_i7kal5q6).

Week 10, day 2: *Reshaping data with `tidyr`, part 2*. Available [here](https://mediaspace.msu.edu/media/Week+10+Day+2/1_75hmqxsu).

Week 11, day 1: *The grammar of graphics*. Available [here](https://mediaspace.msu.edu/media/Week+11+Day+1/1_6us37ay8).

Week 11, day 2: *Final project explanation and more plotting with `ggplot2`*. Available [here](https://mediaspace.msu.edu/media/Week+11+Day+2/1_5meoynmd).

Week 12, day 1: *More plotting with `ggplot2`*. Available [here](https://mediaspace.msu.edu/media/Week+12+Day+1/1_nw3ma983).

Week 12, day 2: *Building graphics incrementally, composing plots with `patchwork`, and saving plots*. Available [here](https://mediaspace.msu.edu/media/Week+12+Day+2/1_jqcpvr2o).

Week 13, day 1: *Spatial data with `sf`*. Available [here](https://mediaspace.msu.edu/media/Week+13+Day+1/1_13u3a4rh).

Week 14, day 1: *Project and midterms and quizzes, galore!* Available [here](https://mediaspace.msu.edu/media/Week+14+Day+1/1_xvw49g8u).

