---
title: "Lab warmup 10/30"
author: "Name: __________________"
editor: source
format:
  pdf:
    margin-top: 2em
---


1. Briefly, describe a sampling distribution and a bootstrap distribution. How are they different? How are they similar? 

\vspace{50mm}



2. We've learned some functions from the `infer` package listed below. For each function, describe its use. Also, for the parameters with `name = _____` describe what these parameters do and some possible values for these parameters. 


`rep_sample_n(.data, n = ______, reps = ______)`

-   rep_sample_n():
\vspace{5mm}
-   n:
-   reps: 

\vspace{10mm}


`specify(x, response = ______, explanatory = ______, success = ______)`

-   specify():
\vspace{5mm}
-   response:
-   explanatory: 
-   success: 


\newpage


`generate(x, reps = ______, type = ______)`

-   generate():
\vspace{5mm}
-   reps:
-   type: 

\vspace{10mm}


`calculate(x, stat = ______, order = ______)`

-   calculate():
\vspace{5mm}
-   stat:
-   order: 

\vspace{10mm}


`visualize(data, bins = ______)`

-   visualize():
\vspace{5mm}
-   bins:

\vspace{10mm}


`get_confidence_interval(x, level = ______ type = ______, point_estimate = ______)`

-   get_confidence_interval():
\vspace{5mm}
-   level:
-   type: 
-   point_estimate:

\vspace{10mm}


`shade_confidence_interval(endpoints = ______)`

-   shade_confidence_interval():
\vspace{5mm}
-   endpoints:

