---
date: 9/15/25
editor: source
---

# Math 141: Readings for {{< meta date >}}

## Reading 

Before coming to lecture today, please read the following material: 

-   MD Chapter 3 (Skip section 3.7). Some of these sections will be review from last time, but I recommend that you read them closely again. 

## Homework Assignment

After you've completed the reading, but before coming to class, please complete the following homework assignment. Bring your responses to this assignment (handwritten or typed) to class on a piece of paper: 

-   LC 3.1, LC 3.2, LC 3.4, LC 3.5, LC 3.9

-   In your own words, explain what each of the `dplyr` verbs we read about in chapter 3 does. No need for more than a sentence or two for each verb. Also, provide an example of using that verb. I've provided a response for one of the verbs as an example:

>| `relocate()`: The relocate verb moves columns around in your dataframe. You can choose which columns to move, and where to move them.
**Example**: You might have a dataframe called cars, with columns "weight" and "mpg", but you want to put the "mpg" column on the left side of the "weight" column. To do this, you could run the following code:
```
cars %>%
  relocate(weight, mpg)
```

