---
date: 11/12/25
editor: source
---

# Math 141: Readings for {{< meta date >}}

## Reading 

Before coming to lecture today, please read the following material: 

-   OI Sections 3.4 and 4.3

## Homework Assignment

After you've completed the reading, but before coming to class, please complete the following homework assignment. Bring your responses to this assignment (handwritten or typed) to class on a piece of paper: 

-   OI Exercises: 3.30, 3.34 (these are at the end of Section 3.4)

-   Suppose 4 students have still not received their graded Math 141 midterm (yes, let's pretend we actually had a hand-written midterm) and that I hand back the exams randomly to each student. Let X = the number of students who get their correct exam.

    a. Let's say the student's names are A(licia), B(ob), C(olin), and D(onna) and they are sitting in a row ABCD. One possible outcome is ABDC (1st exam goes to A, 2nd to B, 3rd to D, 4th to C). In that case, what does X equal?

    b. List out all possible outcomes. And for each outcome, determine what X equals.

    c. Why is P(X = 3) = 0?

    d. Write out the probability distribution for X.

    e. Determine the mean value of X.

    f. Determine the standard deviation of X.

    g. What is the probability that at least one student gets their correct exam?

